apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: {{ .Values.api.replicaSize }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: shadad00/api_image:prod-202311161258
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: PORT
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: POSTGRES_DB
          - name: APP_SETTINGS
            valueFrom: 
              configMapKeyRef:
                name: api-configmap
                key: APP_SETTINGS
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: POSTGRES_USER
          - name: POSTGRES_PASS
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: POSTGRES_PASSWORD
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: api-configmap
                key: DATABASE_URL
