apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL }}