apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{if .Values.client.ssl}}
    cert-manager.io/cluster-issuer: selfsigned-issuer
    {{ end }}
spec:
  rules:
  - host: ejercicio.parcial.santi.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:  
            name: api-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:  
            name: client-service
            port:
              number: 80
  {{if .Values.client.ssl}}
  tls: 
  - hosts:
    - ejercicio.parcial.santi.com
    secretName: certificate-secret 
  {{ end }}
   

